sudo: false
cache:
  directories:
    - node_modules
language: "node_js"
node_js:
  - "6"
  - "7"
matrix:
  include:
    - node_js: "6"
      env: STATIC_CHECKS=true
script:
  - |
    if [ "${STATIC_CHECKS}" = "true" ]; then
      # Just perform static checks and exit
      eslint --max-warnings 0 .
      exit 0
    fi
  - npm run coverage
after_script:
  - npm install -g codecov
  - codecov
